version: "3.8"
services:
  backend:
    build: ./backend
    container_name: transcendence-backend
    env_file:
      - .env
    volumes:
      - backend_data:/app/data
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    container_name: transcendence-frontend
    environment:
      - VITE_API_URL=https://localhost/api
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
  nginx:
    image: nginx:alpine
    container_name: transcendence-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
      - ./certs:/etc/ssl/private:ro
    depends_on:
      - frontend
volumes:
  backend_data:
  frontend_dist:
